name: Placeholder CI

on:
  push:
    branches: main
    paths-ignore:
      - "docs/**"

  pull_request:
    branches: main
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
   
      - name: Set up Python / Node / Ruby / Go / Rust / etc.
        run: echo 'Set up environment here'

      - name: Install dependencies
        run: make install

      - name: Install dev dependencies
        run: make install-dev

      - name: Check formatting
        run: make fmt-check

      - name: Lint
        run: make lint-check

      - name: Run unit tests
        run: make test

      - name: Build
        run: make build
